#!/bin/bash

function build {
    rm -r bin_$1 2> /dev/null
    cmake -B bin_$1 -S src -D $1=true
    cmake --build bin_$1
}

function test {
    sync
    bin_$1/lab2 $2
}

for OptLevel in O0 O1 O2 O3 Os Ofast Og
do
    build $OptLevel
done

for (( i=0; i <= 5; i++ ))
do
    for OptLevel in O0 O1 O2 O3 Os Ofast Og
    do
        echo "Run test with parameters:" $OptLevel $(( 1000000000 + 200000000 * $i ))
        test $OptLevel $(( 1000000000 + 200000000 * $i ))
        echo
    done
done